using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Models.Admission
{
    public class AssignDataBasedOnTabs
    {
        public string SessionValue { get; set; }
        public string CourseType { get; set; }
        public string ApplicantType { get; set; }
        public string RoundOption { get; set; }
        public string Division { get; set; }
        public string District { get; set; }
        public string Taluk { get; set; }
        public string ITIInstitute { get; set; }
        public string SessionValueErr { get; set; }
        public string CourseTypeErr { get; set; }
        public string ApplicantTypeErr { get; set; }
        public string ApplicantionModeErr { get; set; }
        public string RoundOptionErr { get; set; }
        public string DivisionErr { get; set; }
        public string DistrictErr { get; set; }
        public string TalukErr { get; set; }
        public string ITIInstituteErr { get; set; }
        public string PhysicallyHanidcapInd { get; set; }
        public string PhysicallyHanidcapDiv2 { get; set; }
        public string PhysicallyHanidcapType { get; set; }
        public string HoraNaduYes { get; set; }
        public string HoraNaduNo { get; set; }
        public string HoraNadu { get; set; }
        public string ExemptedFromStudyCertificateYes { get; set; }
        public string ExemptedFromStudyCertificateNo { get; set; }
        public string ExemptedFromStudyCertificate { get; set; }
        public string HyderabadKarnatakaRegionYes { get; set; }
        public string HyderabadKarnatakaRegionNo { get; set; }
        public string HyderabadKarnatakaRegion { get; set; }
        public string KanndaMediumYes { get; set; }
        public string KanndaMediumNo { get; set; }
        public string KanndaMedium { get; set; }

        public string EwsYes { get; set; }
        public string EwsNo { get; set; }
        public string Ews { get; set; }

        public string ExServiceYes { get; set; }
        public string ExServiceNo { get; set; }
        public string ExService { get; set; }

        public string RuralUrban { get; set; }
        public string AppBasics { get; set; }
        public string studiedMathsScience { get; set; }
        public string TenthBoard { get; set; }
        public string TenthCOBSEBoard { get; set; }
        public string txtInstituteStudied { get; set; }
        public string txtMaximumMarks { get; set; }
        public string txtMarksObtained { get; set; }
        public string lblPercAsPerMarks { get; set; }
        public string Results { get; set; }
        public string txtCommunicationAddress { get; set; }
        public string Districts { get; set; }
        public string Talukas { get; set; }
        public string txtPincode { get; set; }
        public string chkSameAsCommunicationAddress { get; set; }
        public string txtPermanentAddress { get; set; }
        public string PermanentDistricts { get; set; }
        public string PermanentTalukas { get; set; }
        public string txtPermanentPincode { get; set; }
        public string txtApplicantPhoneNumber { get; set; }
        public string txtFathersPhoneNumber { get; set; }
        public string txtEmailId { get; set; }
        public string DocEduCerAcceptedImg { get; set; }
        public string DocEduCerRejectedImg { get; set; }
        public string EduCertificate { get; set; }
        public string aEduCertificate { get; set; }
        public string EduDocStatus { get; set; }
        public string txtEduCertRemarks { get; set; }
        public string DocCasCerAcceptedImg { get; set; }
        public string DocCasCerRejectedImg { get; set; }
        public string CasteCertificate { get; set; }
        public string aCasteCertificate { get; set; }
        public string CasDocStatus { get; set; }
        public string txtCasteCertRemarks { get; set; }
        public string DocRatCerAcceptedImg { get; set; }
        public string DocRatCerRejectedImg { get; set; }
        public string Rationcard { get; set; }
        public string aRationCard { get; set; }
        public string RationDocStatus { get; set; }
        public string txtRationCardRemarks { get; set; }
        public string DocIncCerAcceptedImg { get; set; }
        public string DocIncCerRejectedImg { get; set; }
        public string Incomecertificate { get; set; }
        public string aIncomeCertificate { get; set; }
        public string IncCerDocStatus { get; set; }
        public string txtIncCertRemarks { get; set; }
        public string DocUIDCerAcceptedImg { get; set; }
        public string DocUIDCerRejectedImg { get; set; }
        public string UIDNumber { get; set; }
        public string aUIDNumber { get; set; }
        public string UIDDocStatus { get; set; }
        public string txtUIDRemarks { get; set; }
        public string DocRurCerAcceptedImg { get; set; }
        public string DocRurCerRejectedImg { get; set; }
        public string Ruralcertificate { get; set; }
        public string RcerDocStatus { get; set; }
        public string txtRurCertRemarks { get; set; }
        public string DocKanMedCerAcceptedImg { get; set; }
        public string DocKanMedCerRejectedImg { get; set; }
        public string KannadamediumCertificate { get; set; }
        public string aKannadamediumCertificate { get; set; }
        public string KanMedCerDocStatus { get; set; }
        public string txtKanMedRemarks { get; set; }
        public string DocDidAblCerAcceptedImg { get; set; }
        public string DocDidAblCerRejectedImg { get; set; }
        public string Differentlyabledcertificate { get; set; }
        public string aDifferentlyabledcertificate { get; set; }
        public string DiffAblDocStatus { get; set; }
        public string txtDiffAbledCertRemarks { get; set; }
        public string DocExStuCerAcceptedImg { get; set; }
        public string DocExStuCerRejectedImg { get; set; }
        public string ExemptedCertificate { get; set; }
        public string aExemptedCertificate { get; set; }
        public string ExCerDocStatus { get; set; }
        public string txtExeCertRemarks { get; set; }
        public string DocHyKarRegAcceptedImg { get; set; }
        public string DocHyKarRegRejectedImg { get; set; }
        public string aHyderabadKarnatakaRegion { get; set; }
        public string HyKarDocStatus { get; set; }
        public string txtHydKarnRemarks { get; set; }
        public string DocHorGadKanAcceptedImg { get; set; }
        public string DocHorGadKanRejectedImg { get; set; }
        public string HoranaaduKannadiga { get; set; }
        public string aHoranaaduKannadiga { get; set; }
        public string HorKanDocStatus { get; set; }
        public string txtHorGadKannadigaRemarks { get; set; }
        public string DocOthCerAcceptedImg { get; set; }
        public string DocOthCerRejectedImg { get; set; }
        public string OtherCertificates { get; set; }
        public string aOtherCertificates { get; set; }
        public string OtherCerDocStatus { get; set; }
        public string txtOtherCertRemarks { get; set; }
        public string DocExSerAcceptedImg { get; set; }
        public string DocExSerRejectedImg { get; set; }
        public string Exserviceman { get; set; }
        public string aExserviceman { get; set; }
        public string ExserDocStatus { get; set; }
        public string txtExservicemanRemarks { get; set; }
        public string DocEWSAcceptedImg { get; set; }
        public string DocEWSRejectedImg { get; set; }
        public string EWSCertificate { get; set; }
        public string aEWSCertificate { get; set; }
        public string aRuralcertificate { get; set; }
        public string EWSDocStatus { get; set; }
        public string txtEWSCertificateRemarks { get; set; }
        public string EDocAppId { get; set; }
        public string ECreatedBy { get; set; }
        public string CDocAppId { get; set; }
        public string CCreatedBy { get; set; }
        public string RDocAppId { get; set; }
        public string RCreatedBy { get; set; }
        public string IDocAppId { get; set; }
        public string ICreatedBy { get; set; }
        public string UDocAppId { get; set; }
        public string UCreatedBy { get; set; }
        public string RUDocAppId { get; set; }
        public string RUCreatedBy { get; set; }
        public string KDocAppId { get; set; }
        public string KCreatedBy { get; set; }
        public string DDocAppId { get; set; }
        public string DCreatedBy { get; set; }
        public string ExDocAppId { get; set; }
        public string ExCreatedBy { get; set; }
        public string HDocAppId { get; set; }
        public string HCreatedBy { get; set; }
        public string HGKDocAppId { get; set; }
        public string HGKCreatedBy { get; set; }
        public string ODocAppId { get; set; }
        public string OCreatedBy { get; set; }
        public string KMDocAppId { get; set; }
        public string KMCreatedBy { get; set; }
        public string ExSDocAppId { get; set; }
        public string ExSCreatedBy { get; set; }
        public string LLDocAppId { get; set; }
        public string LLCreatedBy { get; set; }
        public string EWSDocAppId { get; set; }
        public string EWSCreatedBy { get; set; }
        public string ApplStatus { get; set; }
        public string ApplCredatedBy { get; set; }
        public string ApplFlowId { get; set; }
        public string academicyear2 { get; set; }
        public string ApplicationNumber { get; set; }
        public string ApplicationName { get; set; }
        public string RankNumber { get; set; }
        public string DivisionName { get; set; }
        public string DistrictName { get; set; }
        public string TalukName { get; set; }
        public string MISCode { get; set; }
        public string InstituteName { get; set; }
        public string InstituteType { get; set; }
        public string VerticalCategory { get; set; }
        public string HorizontalCategory { get; set; }
        public string TradeName { get; set; }
        public string Units { get; set; }
        public string Shifts { get; set; }
        public string DualType { get; set; }
        public string TraineeType { get; set; }
        public string ITIUnderPPP { get; set; }
        public string AdmisionTime { get; set; }
        public string AdmisionFee { get; set; }
        public string SaveSeatAllocationFeePay { get; set; }
        public string PaymentGenerationGrid { get; set; }
        public string PaymentDate { get; set; }
        public string ApplicantSeatDetails { get; set; }
        public string AcademicMonths { get; set; }
        public string AcademicYear { get; set; }
        public string academicyear1 { get; set; }
        public string ImgPhotoUpload { get; set; }
        public string IsUploaded { get; set; }
        public string ApplicantId { get; set; }
        public string CredatedBy { get; set; }
        public string txtApplicantName { get; set; }
        public string dateofbirth { get; set; }
        public string txtFathersName { get; set; }
        public string txtMothersName { get; set; }
        public string txtParentOccupation { get; set; }
        public string Gender { get; set; }
        public string txtCaste { get; set; }
        public string Religion { get; set; }
        public string ApplicantTypeSelect { get; set; }
        public string Category { get; set; }
        public string MinorityCategory { get; set; }
        public string txtRationCard { get; set; }
        public string AadhaarNumberDuplicate { get; set; }
        public string txtAadhaarNumber { get; set; }
        public string txtFamilyAnnualIncome { get; set; }
        public string AccountNumber { get; set; }
        public string BankName { get; set; }
        public string IFSCCode { get; set; }
        public string DiffAbledCer { get; set; }
        public string KanMedCer { get; set; }
        public string ExServiceCer { get; set; }
        public string LandLoserCer { get; set; }
        public string EcoWeakCer { get; set; }
        public string KMCer { get; set; }
        public string HoraNaduCer { get; set; }
        public string HydKarCer { get; set; }
        public string ExeStuCer { get; set; }
        public string ApplicableReservations { get; set; }
        public string PhysicallyHanidcapYes { get; set; }
        public string PhysicallyHanidcapNo { get; set; }
        public string PhysicallyHanidcapDiv1 { get; set; }
        public string SearchFrom { get; set; }
        public string DownloadReceipt { get; set; }
        public string AdmFeePaidStatus { get; set; }
        public string ReceiptNumber { get; set; }
        public string AdmissionRegistrationNumber { get; set; }
        public string StateRegistrationNumber { get; set; }
        public string RollNumber { get; set; }
        public string AdmittedStatus { get; set; }
        public string txtRemarks { get; set; }
    }
}
